name: Merge Criteria

on:
  push:

jobs:
    spell-check:
      runs-on: ubuntu-latest

      steps:
        - uses: codespell-project/actions-codespell@v2

    editorconfig:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: editorconfig-checker/action-editorconfig-checker@v2
        - run: editorconfig-checker

    check-pdf-updates:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: ''

        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Run PDF update check
          run: python ci/check_pdf_updates.py
