name: Merge Criteria

on:
  pull_request

jobs:
    spell-check:
      runs-on: ubuntu-latest

      steps:
        - uses: codespell-project/actions-codespell@v2

    
    editorconfig:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: editorconfig-checker/action-editorconfig-checker@main
        - run: editorconfig-checker
